import type { PracticeSession } from '../types'

export const currentSession: PracticeSession = {
  id: '2026-09-22-a2-5-adaptive-v1',
  title: 'A2 Danish practice',
  subtitle: '5 short exercises with longer sentences, clause structure, and active use of fragile vocabulary.',
  level: 'A2',
  evidenceSessionId: '6d6f7c37-f860-4c8a-a81e-202609220001',
  entryIdByWord: {
    'nødvendig': 'a48286b1-3397-43b4-902f-4db06c5938d1',
    'synes': '57dcb4cf-c242-4f18-8f6f-d1bd1881e6e4',
    'besøge': 'fc11eeec-ba4a-4c1f-9391-b79052d5f79d',
    'forklare': 'a45a75e0-5686-48a5-935d-c58eb1532267',
    'nogensinde': 'd902eb17-1cb5-4f87-9975-f8e2f134bd96',
    'skulle': 'eb2d5f3a-60c0-4af0-b0c1-b0344e17112f',
    'afhænge': 'c26c9943-f4e6-4fee-9639-3813b5fa8269',
    'af': '52cb2c7a-3b0f-4e05-8adf-2a1c7ca78778',
  },
  audioByWord: {
    'nødvendig': 'words/noedvendig-01ea4502.mp3',
    'synes': 'words/synes-7721484b.mp3',
    'besøge': 'words/besoege-1335a97c.mp3',
    'forklare': 'words/forklare-9980b50f.mp3',
    'nogensinde': 'words/nogensinde-e7c6616b.mp3',
    'skulle': 'words/skulle-d0f087b7.mp3',
    'afhænge': 'words/afhaenge-0502ebed.mp3',
    'af': 'words/af-d1e62250.mp3',
  },
  suggestedWords: [
    {
      danish: 'hjælp',
      translation: 'помощь',
      example: 'Min bedstemor har brug for hjælp.',
      exampleTranslation: 'Моей бабушке нужна помощь.',
      connectsTo: ['besøge', 'støtte'],
    },
    {
      danish: 'grund',
      translation: 'причина',
      example: 'Kan du forklare grunden?',
      exampleTranslation: 'Можешь объяснить причину?',
      connectsTo: ['forklare', 'hvorfor'],
    },
    {
      danish: 'beslutning',
      translation: 'решение',
      example: 'Beslutningen afhænger af vejret.',
      exampleTranslation: 'Решение зависит от погоды.',
      connectsTo: ['afhænge', 'af'],
    },
  ],
  exercises: [
    {
      id: 'a2-choice-noedvendig',
      type: 'choice',
      title: 'Choose the correct form',
      prompt: 'Jeg synes, det er ___ at tage en jakke med, fordi det er koldt.',
      options: ['nødvendigt', 'nødvendig', 'nødvendige'],
      answer: 'nødvendigt',
      glosses: {
        'tage': 'брать',
        'jakke': 'куртка',
        'koldt': 'холодно',
      },
      focusWords: ['nødvendig', 'synes'],
      evidenceWords: ['nødvendig'],
      evidenceSkill: 'grammar',
      explanation: 'After “det er”, the adjective uses the neuter form: nødvendigt.',
    },
    {
      id: 'a2-order-besoeg',
      type: 'order',
      title: 'Build the sentence',
      instruction: 'Build a natural sentence with fordi.',
      tokens: ['fordi', 'hun', 'har', 'brug', 'for', 'hjælp.', 'Jeg', 'besøger', 'min', 'bedstemor,'],
      answer: ['Jeg', 'besøger', 'min', 'bedstemor,', 'fordi', 'hun', 'har', 'brug', 'for', 'hjælp.'],
      focusWords: ['besøge'],
      evidenceWords: ['besøge'],
      evidenceSkill: 'word-order',
      explanation: 'After fordi, the subject still comes before the verb: fordi hun har brug for hjælp.',
    },
    {
      id: 'a2-dialogue-forklare',
      type: 'dialogue',
      title: 'Choose the natural reply',
      speakerA: 'Jeg forstår ikke, hvorfor mødet er flyttet.',
      speakerBPrompt: 'Ask the other person to explain why.',
      options: [
        'Kan du forklare, hvorfor det er flyttet?',
        'Kan du besøge, hvorfor det er flyttet?',
        'Kan du få, hvorfor det er flyttet?',
      ],
      answer: 'Kan du forklare, hvorfor det er flyttet?',
      glosses: {
        'mødet': 'встреча',
        'flyttet': 'перенесена',
      },
      focusWords: ['forklare'],
      evidenceWords: ['forklare'],
      evidenceSkill: 'communication',
      explanation: 'forklare is the natural verb when you ask someone to explain something.',
    },
    {
      id: 'a2-type-nogensinde',
      type: 'type',
      title: 'Write the Danish sentence',
      prompt: 'Write in Danish: “Тебе когда-нибудь приходилось работать в воскресенье?”',
      accepted: [
        'Har du nogensinde skullet arbejde på en søndag?',
        'Har du nogensinde skullet arbejde på en søndag',
      ],
      placeholder: 'Har du …',
      answerLabel: 'Answer',
      focusWords: ['nogensinde', 'skulle'],
      evidenceWords: ['nogensinde', 'skulle'],
      evidenceSkill: 'production',
      explanation: 'Har du nogensinde skullet … combines “ever” with the perfect form of skulle.',
    },
    {
      id: 'a2-drag-afhaenge',
      type: 'drag-gap',
      title: 'Complete the expression',
      before: 'Det afhænger',
      after: ', om vi har tid.',
      options: ['af', 'til', 'om'],
      answer: 'af',
      glosses: {
        'tid': 'время',
      },
      focusWords: ['afhænge', 'af'],
      evidenceWords: ['afhænge', 'af'],
      evidenceSkill: 'collocation',
      explanation: 'The fixed expression is “det afhænger af …”.',
    },
  ],
}
