import type { PracticeSession } from '../types'

export const currentSession: PracticeSession = {
  id: '2026-09-22-a1-35-adaptive-v1',
  title: 'Today’s Danish practice',
  subtitle: '35 A1 exercises focused on fragile words, active use, and a few useful new words.',
  level: 'A1',
  exercises: [
    {
      id: 'match-core-weak', type: 'match', title: 'Match the meanings',
      pairs: [
        { left: 'nødvendig', right: 'необходимый / нужный' },
        { left: 'få', right: 'получать' },
        { left: 'besøge', right: 'навещать / посещать' },
        { left: 'slå', right: 'ударить / бить' },
      ],
      focusWords: ['nødvendig','få','besøge','slå'],
      explanation: 'These words have caused repeated mistakes, so start with quick recognition.',
    },
    {
      id: 'choice-faa-besked', type: 'choice', title: 'Choose the right word',
      prompt: 'Jeg ___ en besked.', options: ['får','slår','besøger'], answer: 'får',
      glosses: { besked: 'сообщение' },
      focusWords: ['få'], explanation: 'Jeg får en besked. = Я получаю сообщение.',
    },
    {
      id: 'dialogue-besoeg', type: 'dialogue', title: 'Choose what fits',
      speakerA: 'Hvad laver du i weekenden?', speakerBPrompt: 'You want to say you are visiting your grandmother.',
      glosses: { laver: 'делаешь', weekenden: 'выходные' },
      options: ['Jeg besøger min bedstemor.','Jeg får min bedstemor.','Jeg slår min bedstemor.'],
      answer: 'Jeg besøger min bedstemor.',
      focusWords: ['besøge'], explanation: 'besøge means to visit.',
    },
    {
      id: 'binary-bange', type: 'binary', title: 'True or false?',
      statement: '“Jeg er bange for hunde.” means “Я боюсь собак.”', correct: true,
      glosses: { hunde: 'собаки' },
      focusWords: ['bange'], explanation: 'The common pattern is være bange for + something.',
    },
    {
      id: 'type-kun', type: 'type', title: 'Fill the missing word',
      prompt: 'Jeg har ___ ti minutter. (только)', accepted: ['kun'],
      glosses: { minutter: 'минуты' },
      placeholder: 'one word', answerLabel: 'Answer',
      focusWords: ['kun'], explanation: 'kun = only.',
    },
    {
      id: 'drag-lige', type: 'drag-gap', title: 'Complete the sentence',
      before: 'Jeg er', after: 'kommet hjem.', options: ['lige','kun','tit'], answer: 'lige',
      glosses: { kommet: 'пришёл / приехал', hjem: 'домой' },
      focusWords: ['lige'], explanation: 'lige can mean “just / just now”: Jeg er lige kommet hjem.',
    },
    {
      id: 'order-hvordan', type: 'order', title: 'Build the question',
      tokens: ['det?','du','Hvordan','har'], answer: ['Hvordan','har','du','det?'],
      focusWords: ['hvordan'], explanation: 'Hvordan har du det? = Как ты?',
    },
    {
      id: 'match-modals', type: 'match', title: 'Match the words',
      pairs: [
        { left: 'kunne', right: 'мочь / уметь' },
        { left: 'skulle', right: 'должен был / следовало' },
        { left: 'tit', right: 'часто' },
        { left: 'stadig', right: 'всё ещё' },
      ],
      focusWords: ['kunne','skulle','tit','stadig'],
      explanation: 'These are common words that are still fragile in recall.',
    },
    {
      id: 'choice-kunne', type: 'choice', title: 'Choose the natural word',
      prompt: 'Det er godt at ___ svømme.', options: ['kunne','skulle','slå'], answer: 'kunne',
      glosses: { godt: 'хорошо', svømme: 'плавать' },
      focusWords: ['kunne'], explanation: 'at kunne svømme = уметь плавать.',
    },
    {
      id: 'choice-skulle', type: 'choice', title: 'Choose the natural word',
      prompt: 'Jeg ___ arbejde i går.', options: ['skulle','kunne','tit'], answer: 'skulle',
      glosses: { arbejde: 'работать', 'i går': 'вчера' },
      focusWords: ['skulle'], explanation: 'Jeg skulle arbejde i går. = Я должен был работать вчера.',
    },
    {
      id: 'listen-nogensinde', type: 'listen-choice', title: 'Listen and choose',
      text: 'Har du nogensinde været i Sverige?',
      options: ['Ты когда-нибудь был в Швеции?','Ты сейчас в Швеции?','Ты часто ездишь в Швецию?'],
      answer: 'Ты когда-нибудь был в Швеции?',
      focusWords: ['nogensinde'],
      explanation: 'nogensinde often means “ever” in questions.',
    },
    {
      id: 'type-noedvendig', type: 'type', title: 'Complete the sentence',
      prompt: 'Det er ___ at have billet. (необходимо)', accepted: ['nødvendigt'],
      glosses: { billet: 'билет' },
      placeholder: 'one word', answerLabel: 'Answer',
      focusWords: ['nødvendig'], explanation: 'With det er, the adjective takes the neuter form: nødvendigt.',
    },
    {
      id: 'odd-prepositions', type: 'odd-one-out', title: 'Odd one out',
      prompt: 'Three are prepositions. One is a verb.',
      items: ['til','af','om','besøge'], answer: 'besøge',
      focusWords: ['til','af','om'], explanation: 'til, af and om are prepositions. besøge is a verb.',
    },
    {
      id: 'sort-prepositions', type: 'category-sort', title: 'Sort the words',
      categories: ['Preposition','Not a preposition'],
      items: [
        { text: 'til', category: 'Preposition' },
        { text: 'om', category: 'Preposition' },
        { text: 'af', category: 'Preposition' },
        { text: 'stadig', category: 'Not a preposition' },
        { text: 'synes', category: 'Not a preposition' },
      ],
      focusWords: ['til','om','af','stadig','synes'],
      explanation: 'til, om and af are prepositions.',
    },
    {
      id: 'dialogue-forklare', type: 'dialogue', title: 'Choose the reply',
      speakerA: 'Jeg forstår det ikke.', speakerBPrompt: 'Ask the person to explain it.',
      glosses: { forstår: 'понимаю' },
      options: ['Kan du forklare det?','Kan du besøge det?','Kan du slå det?'],
      answer: 'Kan du forklare det?',
      focusWords: ['forklare'], explanation: 'Kan du forklare det? = Можешь это объяснить?',
    },
    {
      id: 'type-synes', type: 'type', title: 'Fill the missing word',
      prompt: 'Jeg ___, det er godt.', accepted: ['synes'],
      placeholder: 'one word', answerLabel: 'Answer',
      focusWords: ['synes'], explanation: 'Jeg synes, det er godt. = Я думаю, что это хорошо.',
    },
    {
      id: 'choice-sand', type: 'choice', title: 'Choose the right form',
      prompt: 'Det er ___ .', options: ['sandt','sand','sande'], answer: 'sandt',
      focusWords: ['sand'], explanation: 'With det, use the neuter form: sandt.',
    },
    {
      id: 'binary-stoette', type: 'binary', title: 'True or false?',
      statement: '“Han støtter mig.” means “Он меня поддерживает.”', correct: true,
      focusWords: ['støtte'], explanation: 'støtte can mean to support.',
    },
    {
      id: 'order-gerne', type: 'order', title: 'Build the sentence',
      tokens: ['kaffe.','gerne','Jeg','vil','have'], answer: ['Jeg','vil','gerne','have','kaffe.'],
      focusWords: ['gerne'], explanation: 'Jeg vil gerne have kaffe. is a common polite pattern.',
    },
    {
      id: 'drag-tit', type: 'drag-gap', title: 'Complete the sentence',
      before: 'Jeg ser mine venner', after: '.', options: ['tit','kun','til'], answer: 'tit',
      glosses: { venner: 'друзья' },
      focusWords: ['tit'], explanation: 'tit = often.',
    },
    {
      id: 'listen-hvordan', type: 'listen-choice', title: 'Listen and choose',
      text: 'Hvordan har du det?',
      options: ['Как ты?','Где ты живёшь?','Что ты делаешь?'], answer: 'Как ты?',
      focusWords: ['hvordan'], explanation: 'Recognise Hvordan har du det? as one useful chunk.',
    },
    {
      id: 'flash-afhaenge', type: 'flash-reveal', title: 'Recall the meaning',
      prompt: 'Det afhænger af vejret.', answer: 'Это зависит от погоды.',
      glosses: { vejret: 'погода' },
      focusWords: ['afhænge'], explanation: 'The useful phrase is: Det afhænger af …',
    },
    {
      id: 'choice-nogen', type: 'choice', title: 'Choose the right word',
      prompt: 'Er der ___ hjemme?', options: ['nogen','nogensinde','kun'], answer: 'nogen',
      glosses: { hjemme: 'дома' },
      focusWords: ['nogen'], explanation: 'Er der nogen hjemme? = Есть кто-нибудь дома?',
    },
    {
      id: 'match-new-common', type: 'match', title: 'Match useful new words',
      pairs: [
        { left: 'mere', right: 'больше / ещё' },
        { left: 'nu', right: 'сейчас' },
        { left: 'ud', right: 'наружу' },
        { left: 'også', right: 'тоже / также' },
      ],
      focusWords: ['mere','nu','ud','også'],
      explanation: 'These are high-frequency A1 words from your new set.',
    },
    {
      id: 'choice-mere', type: 'choice', title: 'Choose the right word',
      prompt: 'Jeg vil gerne have ___ vand.', options: ['mere','nu','ud'], answer: 'mere',
      focusWords: ['mere'], explanation: 'mere vand = more water.',
    },
    {
      id: 'drag-nu', type: 'drag-gap', title: 'Complete the sentence',
      before: 'Jeg spiser', after: '.', options: ['nu','ud','også'], answer: 'nu',
      focusWords: ['nu'], explanation: 'Jeg spiser nu. = Я ем сейчас.',
    },
    {
      id: 'order-ogsaa', type: 'order', title: 'Build the sentence',
      tokens: ['også.','Jeg','kommer'], answer: ['Jeg','kommer','også.'],
      focusWords: ['også','komme'], explanation: 'Jeg kommer også. = Я тоже приду.',
    },
    {
      id: 'type-se', type: 'type', title: 'Fill the missing verb',
      prompt: 'Jeg kan ___ dig.', accepted: ['se'],
      placeholder: 'one word', answerLabel: 'Answer',
      focusWords: ['se'], explanation: 'Jeg kan se dig. = Я могу тебя видеть.',
    },
    {
      id: 'choice-ny', type: 'choice', title: 'Choose the right word',
      prompt: 'Jeg har en ___ cykel.', options: ['ny','mere','nu'], answer: 'ny',
      glosses: { cykel: 'велосипед' },
      focusWords: ['ny'], explanation: 'en ny cykel = a new bicycle.',
    },
    {
      id: 'dialogue-sige', type: 'dialogue', title: 'Choose what to say',
      speakerA: 'Jeg forstår ikke.', speakerBPrompt: 'Ask them to say it again.',
      glosses: { forstår: 'понимаю' },
      options: ['Kan du sige det igen?','Kan du se det igen?','Kan du gå det igen?'],
      answer: 'Kan du sige det igen?',
      focusWords: ['sige'], explanation: 'Kan du sige det igen? = Можешь сказать это ещё раз?',
    },
    {
      id: 'listen-gaa', type: 'listen-choice', title: 'Listen and choose',
      text: 'Vi går hjem nu.',
      options: ['Мы идём домой сейчас.','Мы видим дом сейчас.','Мы остаёмся дома.'],
      answer: 'Мы идём домой сейчас.',
      focusWords: ['gå','nu'],
      explanation: 'går is the present form of gå.',
    },
    {
      id: 'type-hvor', type: 'type', title: 'Complete the question',
      prompt: '___ bor du?', accepted: ['Hvor','hvor'],
      placeholder: 'one word', answerLabel: 'Answer',
      focusWords: ['hvor'], explanation: 'Hvor bor du? = Где ты живёшь?',
    },
    {
      id: 'sort-new-verbs', type: 'category-sort', title: 'Sort the new words',
      categories: ['Verb','Not a verb'],
      items: [
        { text: 'se', category: 'Verb' },
        { text: 'gå', category: 'Verb' },
        { text: 'sige', category: 'Verb' },
        { text: 'nu', category: 'Not a verb' },
        { text: 'også', category: 'Not a verb' },
        { text: 'mere', category: 'Not a verb' },
      ],
      focusWords: ['se','gå','sige','nu','også','mere'],
      explanation: 'se, gå and sige are verbs.',
    },
    {
      id: 'flash-stadig', type: 'flash-reveal', title: 'Recall the meaning',
      prompt: 'stadig', answer: 'всё ещё / по-прежнему',
      focusWords: ['stadig'], explanation: 'Example: Jeg lærer stadig dansk.',
    },
    {
      id: 'type-stadig-sentence', type: 'type', title: 'Write the short sentence',
      prompt: 'Write in Danish: “Я всё ещё учу датский.”',
      accepted: ['Jeg lærer stadig dansk.','Jeg lærer stadig dansk'],
      placeholder: 'Jeg …', answerLabel: 'Answer',
      focusWords: ['stadig','dansk'],
      explanation: 'Jeg lærer stadig dansk. = Я всё ещё учу датский.',
    },
  ],
}
