import type { PracticeSession } from '../types'

export const currentSession: PracticeSession = {
  id: '2026-09-22-light-a2-10-adaptive-v1',
  title: 'Light A2 Danish practice',
  subtitle: '10 short exercises with practical vocabulary, light word order, collocations, and active recall.',
  level: 'A2',
  evidenceSessionId: '9b780ca5-3ad6-4a5b-a8cd-8c429f3d5b7e',
  entryIdByWord: {
    'gerne': '59471451-bdc0-422c-a428-29e27429ee39',
    'få': '5d953794-6629-4b20-b846-e1f797e57c83',
    'støtte': '510a7e1e-4218-45b2-a4f7-5b34472620ab',
    'sidste': '5c66b5a3-ab22-44d7-9f4d-3f74d74c818c',
    'tit': 'f610b6a0-9dfb-44ea-9033-5248c3242024',
    'uanset': 'af5e1570-0a93-4fae-bed1-49d0b7af666d',
    'vigtig': 'da7b08e5-2488-444c-b6f3-9b16782b55e8',
    'bange': '5555dd4b-2165-4df9-bb2c-b84efdaf9a89',
    'nogen': '029d4b7c-7aab-4760-ae0e-07ee12a94b77',
    'kunne': '9520a38b-111d-422d-9136-7f8190ad8dc3',
  },
  audioByWord: {
    'gerne': 'words/gerne-7c4810f7.mp3',
    'få': 'words/faa-8221ae99.mp3',
    'støtte': 'words/stoette-4fdf9e01.mp3',
    'sidste': 'words/sidste-1feeed4c.mp3',
    'tit': 'words/tit-037b3e93.mp3',
    'uanset': 'words/uanset-2f79bc9b.mp3',
    'vigtig': 'words/vigtig-ccfb0cca.mp3',
    'bange': 'words/bange-4d8a3ed3.mp3',
    'nogen': 'words/nogen-22122426.mp3',
    'kunne': 'words/kunne-b0f60f83.mp3',
  },
  suggestedWords: [
    {
      danish: 'hjælpe',
      translation: 'помогать',
      example: 'Kan du hjælpe mig med kassen?',
      exampleTranslation: 'Ты можешь помочь мне с коробкой?',
      connectsTo: ['nogen', 'støtte'],
    },
    {
      danish: 'svar',
      translation: 'ответ',
      example: 'Jeg venter på et svar.',
      exampleTranslation: 'Я жду ответа.',
      connectsTo: ['få'],
    },
    {
      danish: 'rolig',
      translation: 'спокойный',
      example: 'Jeg prøver at være rolig, når jeg er bange.',
      exampleTranslation: 'Я стараюсь быть спокойным, когда мне страшно.',
      connectsTo: ['bange'],
    },
  ],
  exercises: [
    {
      id: 'light-a2-choice-gerne',
      type: 'choice',
      title: 'Choose the natural word',
      prompt: 'Tak for invitationen. Jeg vil ___ med.',
      options: ['gerne', 'aldrig', 'stadig'],
      answer: 'gerne',
      glosses: {
        'invitationen': 'приглашение',
      },
      focusWords: ['gerne'],
      evidenceWords: ['gerne'],
      evidenceSkill: 'meaning',
      explanation: '“Jeg vil gerne med” means that you would like to come along.',
    },
    {
      id: 'light-a2-drag-faa',
      type: 'drag-gap',
      title: 'Complete the sentence',
      before: 'Jeg håber at',
      after: 'svar i morgen.',
      options: ['få', 'tage', 'gå'],
      answer: 'få',
      glosses: {
        'svar': 'ответ',
        'morgen': 'завтра',
      },
      focusWords: ['få'],
      evidenceWords: ['få'],
      evidenceSkill: 'collocation',
      explanation: 'The natural expression is “få svar” — to get an answer.',
    },
    {
      id: 'light-a2-match-fragile',
      type: 'match',
      title: 'Match the meanings',
      pairs: [
        { left: 'støtte', right: 'поддержка' },
        { left: 'vigtig', right: 'важный' },
        { left: 'bange', right: 'испуганный' },
        { left: 'sidste', right: 'последний' },
      ],
      focusWords: ['støtte', 'vigtig', 'bange', 'sidste'],
      evidenceWords: ['støtte', 'vigtig', 'bange', 'sidste'],
      evidenceSkill: 'meaning',
      explanation: 'These four words are still fragile, so this is a quick recognition check.',
    },
    {
      id: 'light-a2-order-tit',
      type: 'order',
      title: 'Build the sentence',
      instruction: 'Put the adverb in a natural position.',
      tokens: ['Vi', 'går', 'tit', 'en', 'tur.'],
      answer: ['Vi', 'går', 'tit', 'en', 'tur.'],
      focusWords: ['tit'],
      evidenceWords: ['tit'],
      evidenceSkill: 'word-order',
      explanation: 'In a simple main clause, “tit” normally comes after the finite verb: “Vi går tit …”.',
    },
    {
      id: 'light-a2-binary-uanset',
      type: 'binary',
      title: 'True or false?',
      statement: '“Uanset vejret” betyder, at vejret ikke ændrer planen.',
      correct: true,
      trueLabel: 'True',
      falseLabel: 'False',
      glosses: {
        'vejret': 'погода',
        'ændrer': 'меняет',
        'planen': 'план',
      },
      focusWords: ['uanset'],
      evidenceWords: ['uanset'],
      evidenceSkill: 'meaning',
      explanation: '“Uanset” means regardless of something: the weather does not change the plan.',
    },
    {
      id: 'light-a2-dialogue-nogen',
      type: 'dialogue',
      title: 'Choose the natural question',
      speakerA: 'Jeg kan ikke løfte kassen alene.',
      speakerBPrompt: 'Ask whether someone can help.',
      options: [
        'Er der nogen, der kan hjælpe?',
        'Er der sidste, der kan hjælpe?',
        'Er der vigtig, der kan hjælpe?',
      ],
      answer: 'Er der nogen, der kan hjælpe?',
      glosses: {
        'løfte': 'поднять',
        'kassen': 'коробку',
        'alene': 'один',
      },
      focusWords: ['nogen'],
      evidenceWords: ['nogen'],
      evidenceSkill: 'communication',
      explanation: '“Er der nogen …?” is the natural way to ask whether somebody is available.',
    },
    {
      id: 'light-a2-type-vigtig',
      type: 'type',
      title: 'Write it in Danish',
      prompt: 'Напиши по-датски: «Это важно».',
      accepted: ['Det er vigtigt', 'Det er vigtigt.'],
      placeholder: 'Det er …',
      answerLabel: 'Answer',
      focusWords: ['vigtig'],
      evidenceWords: ['vigtig'],
      evidenceSkill: 'grammar',
      explanation: 'With “det”, the adjective takes the neuter form: “Det er vigtigt.”',
    },
    {
      id: 'light-a2-type-bange',
      type: 'type',
      title: 'Write the expression',
      prompt: 'Напиши по-датски: «Я боюсь собак».',
      accepted: ['Jeg er bange for hunde', 'Jeg er bange for hunde.'],
      placeholder: 'Jeg er …',
      answerLabel: 'Answer',
      focusWords: ['bange'],
      evidenceWords: ['bange'],
      evidenceSkill: 'production',
      explanation: 'The fixed pattern is “være bange for” — to be afraid of.',
    },
    {
      id: 'light-a2-choice-sidste',
      type: 'choice',
      title: 'Choose the time word',
      prompt: 'Jeg var i København i ___ uge, men ikke i denne uge.',
      options: ['sidste', 'næste', 'hver'],
      answer: 'sidste',
      glosses: {
        'denne': 'эта',
      },
      focusWords: ['sidste'],
      evidenceWords: ['sidste'],
      evidenceSkill: 'meaning',
      explanation: '“I sidste uge” means last week.',
    },
    {
      id: 'light-a2-reveal-kunne',
      type: 'flash-reveal',
      title: 'Active recall',
      prompt: 'Hvordan siger man på dansk: «мочь / уметь»?',
      answer: 'kunne',
      knownLabel: 'I knew it',
      unknownLabel: 'Need practice',
      focusWords: ['kunne'],
      evidenceWords: ['kunne'],
      evidenceSkill: 'recall',
      explanation: '“kunne” is the infinitive form; in the present tense it is “kan”.',
    },
  ],
}
